# Generated by Django 4.0.4 on 2022-06-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='name')),
                ('height', models.IntegerField(verbose_name='height')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('types', models.CharField(max_length=200, verbose_name='types')),
                ('sprint', models.CharField(max_length=200, verbose_name='sprint')),
            ],
        ),
    ]
